version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "cloudformation build ec2"
          command: |
            aws cloudformation deploy \
              --stack-name newEC2 --template-body template.yml \
              --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" \
            
workflows:
  cloudformation-ec2:
    jobs:
      - create_infrastructure
