# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  delete_stack:
    steps:
      - run:
          name: destroy stack on failure
          when: on_fail
          command: |
            aws cloudformation delete-stack ec2stack
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "cloudformation build ec2"
          command: |
            aws cloudformation deploy \
              --template-file .circleci/template.yml \
              --stack-name ec2stack
      - run: exit 1
      - delete_stack

workflows:
  # Name the workflow "create_delete"
  create_delete:
    jobs:
      - create_infrastructure
