version: 2.1

commands:
  delete_stack:
    steps:
      - run:
          name: destroy stack on failure
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "cloudformation build ec2"
          command: |
            aws cloudformation deploy \
              --stack-name newEC2 --template-file .circleci/template.yml \

  destroy_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      -checkout
      - run:
          name: create error
          command: |
            return 1
      - delete_stack
        when: on_fail
            
workflows:
  cloudformation-ec2:
    jobs:
      - create_infrastructure
      - destroy_infrastructure
