# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  delete_stack:
    steps:
      - run:
          name: destroy stack on failure
          command: aws cloudformation delete-stack newEC2
          when: on_fail
jobs:
  build:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: "build stack2"
          command: |
            aws cloudformation deploy \
              --template-file .circleci/template.yml \
              --stack-name newEC2
      - delete_stack

workflows:
  # Name the workflow "create_delete"
  create_delete:
    jobs:
      - build
